name: Experiments

on: [push]

jobs:
  build_job_1:
    name: Job 1
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check build dependencies
      run: |
        python --version
        git --version
        docker --version
    
    - name: Do some stuff
      run: |
        echo 'job 1' >> job-files/job_file_1
    
    - name: Archive Job 1
      uses: actions/upload-artifact@v1.0.0
      with:
        name: job_1
        path: job-files/job_file_1
  
  build_job_2:
    name: Job 2
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check build dependencies
      run: |
        python --version
        git --version
        docker --version
    
    - name: Do some stuff
      run: |
        echo 'job 2' >> job-files/job_file_2
    
    - name: Archive Job 2
      uses: actions/upload-artifact@v1.0.0
      with:
        name: job_2
        path: job-files/job_file_2

  build_job_3:
    name: Job 3
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check build dependencies
      run: |
        python --version
        git --version
        docker --version
    
    - name: Do some stuff
      run: |
        echo 'job 3' >> job-files/job_file_3
    
    - name: Archive Job 3
      uses: actions/upload-artifact@v1.0.0
      with:
        name: job_3
        path: job-files/job_file_3

  merge_jobs:
    name: Merge jobs
    needs: [build_job_1, build_job_2, build_job_3]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Download Job 1 artifact
      uses: actions/download-artifact@v1
      with:
        name: job_1

    - name: Download Job 2 artifact
      uses: actions/download-artifact@v1
      with:
        name: job_2

    - name: Download Job 3 artifact
      uses: actions/download-artifact@v1
      with:
        name: job_3

    - name: Concatenate the jobs into a single job
      run: |
        job_1_value=`cat job_3/job_file_1`
        job_2_value=`cat job_3/job_file_3`
        job_3_value=`cat job_3/job_file_3`

        pwd
        ls -la .
        ls -la jobs_files

        echo $job_1_value >> job_files/merged_jobs
        echo $job_2_value >> job_files/merged_jobs
        echo $job_3_value >> job_files/merged_jobs

    - name: on pull request
      if: github.event_name == 'pull_request'
      run: echo 'executed on pull request'

    - name: on master
      if: github.ref == 'refs/heads/master'
      run: echo 'executed only on master branch'

    - name: Archive Merged jobs
      uses: actions/upload-artifact@v1.0.0
      with:
        name: jobs
        path: job_files/merged_jobs