name: Tests

on: [push]

jobs:
  linux_test:
    name: Linux Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check Java version
      run: |
        java -version
    
    - name: Run test
      run: |
         javac -cp .:deps/linux.jar src/Main.java
         java -cp .:deps/linux.jar src/Main

  macos_test:
    name: macOS Test
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: check Java version
      run: |
        java -version
    
    - name: Run test
      run: |
         javac -cp .:deps/macos.jar src/Main.java
         java -cp .:deps/macos.jar src/Main