name: Build V8 7.4.288

on: [push]

jobs:
  build_v8_win:
    name: V8 build for Windows
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 2.x
      uses: actions/setup-python@v1
      with:
        python-version: '2.x'
    - name: check build dependencies
      run: |
        python --version
        git --version

    - name: Build V8 for Windows
      run: |
        mkdir -p v8build
        cd v8build
        $(get-location)
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        $env:Path += ";$(get-location)\depot_tools"
        $env
        $env:Path

        $env:SKIP_V8_GYP_ENV=1
        $env:DEPOT_TOOLS_WIN_TOOLCHAIN=0
        $env:GYP_MSVS_VERSION=2019
        gclient.bat

        fetch.bat v8
        cd v8
        git checkout 7.4.288
    
    - name: Archive V8 monolith
      uses: actions/upload-artifact@v1.0.0
      with:
        name: v8-win-64-monolith
        path: v8build/v8/out.gn/x64.release/obj/libv8_monolith.a
