name: Build V8

on: [push]

jobs:
  build_v8_android_all:
    name: V8 for Android
    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: check build dependencies
      run: |
        python --version
        git --version
        docker --version

    - name: Download V8 monolithic static library for Android (arm64, arm, x86_64, x86)
      run: |
        curl -O https://download.eclipsesource.com/j2v8/v8/libv8_7.4.288_monolith.zip
        mkdir -p v8.out
        unzip libv8_7.4.288_monolith.zip -d v8.out
    
        ls -lR v8.out
